# server
server:
  port: 8080
  host: localhost
  
# database  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/musinsaDB?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: password
    
  jpa:
    hibernate:  
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show-sql: true